name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  component_save_annotation:
    path: ../../component_save_annotation/
  firebase_core: ^3.5.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner:
  component_save_generator:
    path: ../../component_save_generator/
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
